Dim BOARD_OUTLINE_LAYER
Dim TOP_MECH_BODY_LAYER
Dim MIN_TENTED_VIA_RATIO

Sub ConfigInit()
	BOARD_OUTLINE_LAYER = eMechanical1
	TOP_MECH_BODY_LAYER = eMechanical13
    MIN_TENTED_VIA_RATIO = 0.90
End Sub
