Dim BOARD_OUTLINE_LAYER
Dim PCB_INFO_LAYER
Dim TOP_DIMENSIONS_LAYER
Dim BOT_DIMENSIONS_LAYER
Dim TOP_MECH_BODY_LAYER
Dim BOT_MECH_BODY_LAYER
Dim TOP_COURTYARD_LAYER
Dim BOT_COURTYARD_LAYER
Dim MIN_TENTED_VIA_RATIO

Sub ConfigInit()
    ' BOARD LAYERS
	BOARD_OUTLINE_LAYER 	= eMechanical1
    PCB_INFO_LAYER			= eMechanical2
    TOP_DIMENSIONS_LAYER 	= eMechanical11
    BOT_DIMENSIONS_LAYER 	=  eMechanical12
    TOP_MECH_BODY_LAYER 	= eMechanical13
    BOT_MECH_BODY_LAYER 	= eMechanical14
    TOP_COURTYARD_LAYER		= eMechanical15
    BOT_COURTYARD_LAYER     = eMechanical16

    MIN_TENTED_VIA_RATIO 	= 0.90
End Sub
